### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by redapple0204** [lzjqsdd/WifiAssist#10]
cp: 无法获取'WifiAssist' 的文件状态(stat): 没有那个文件或目录

**Comment by lzjqsdd** [comment]
最新的提交关于自动更新和托盘唤醒功能的还没修改完，请先下载https://github.com/lzjqsdd/WifiAssist/archive/v0.6.3.zip

**Comment by redapple0204** [comment]
@lzjqsdd 谢谢，可以打开了
