### ISSUE TITLE
无法开启wifi

### ISSUE THREAD

**Issue by redapple0204** [lzjqsdd/WifiAssist#11]
请问是否贵项目不支持在wifi网络连接下开启wifi热点，不管选择什么网卡，都会出现
<br />>Running as Daemon...
<br />ERROR: 'wlp0s29u1u1' is not a WiFi interface
<br />Trying to kill wifi.sh instance associated with wlp0s29u1u1...
<br />Running as Daemon...
<br />ERROR: 'wlp0s29u1u1' is not a WiFi interface
<br />Trying to kill wifi.sh instance associated with enp3s0...
<br />Running as Daemon...
<br />ERROR: 'enp3s0' is not a WiFi interface
<br />Trying to kill wifi.sh instance associated with enp3s0...
<br />Running as Daemon...
<br />ERROR: 'wlp0s29u1u1' is not a WiFi interface
<br />Trying to kill wifi.sh instance associated with wlp0s29u1u1...

**Comment by lzjqsdd** [comment]
在deepin上有反馈过相关问题，但是在ubuntu下测试可以，该问题已经记录。

**Comment by redapple0204** [comment]
@lzjqsdd 这是在arch上出现的

**Comment by lzjqsdd** [comment]
谢谢反馈
