### ISSUE TITLE
安装不上

### ISSUE THREAD

**Issue by jiuxiaxixi** [lzjqsdd/WifiAssist#13]
zxy@zxy-pc:~/software/WifiAssist/INSTALL$ sudo ./install.sh 
[sudo] zxy 的密码：
Install WifiAssist ...
cp: 无法获取'WifiAssist' 的文件状态(stat): 没有那个文件或目录
Done.

**Comment by lzjqsdd** [comment]
请参考 #10

**Comment by jiuxiaxixi** [comment]
感谢

lzjqsdd notifications@github.com于2016年8月17日周三 上午9:38写道：
