### ISSUE TITLE
电脑有线连接，开启wifi后手机搜索不到

### ISSUE THREAD

**Issue by xyz1001** [lzjqsdd/WifiAssist#19]
电脑有线连接，开启wifi后手机搜索不到

**Comment by lzjqsdd** [comment]
在终端下执行，把日志信息反馈下。

**Comment by boystar1988** [comment]
同上   没有输出错误信息

**Comment by boystar1988** [comment]
同上，提示：Refusing to render service to dead parents.

**Comment by lzjqsdd** [comment]
这个问题已经找到原因了，最近工作比较忙，得过段时间来做，不好意思，如果有兴趣可以帮忙解决下。
