### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by soenter** [lzjqsdd/WifiAssist#2]
/usr/local/bin/WifiAssist: 行 3:  4401 段错误               pkexec --user root /usr/local/WifiAssist/WifiAssist

**Comment by lzjqsdd** [comment]
你好请问使用的是最新的这个么？这个问题在0.1的时候出现过，需要单独自定义PolicyKit文件。如果使用.install.sh安装的话应该会把授权配置文件添加进去，请检查下:
/usr/share/polkit-1/actions目录下有没有com.lzjqsdd.WifiAssist.policy文件。

如果不行的化，可以下按照一下方式处理:

`sudo rm  /usr/local/bin/WifiAssist`
`sudo ln -s /usr/local/WifiAssist/WifiAssist /usr/local/bin/WifiAssist`

然后只能在终端以sudo WifiAssist来执行，暂时无法通过图形界面来授权，因为wifi创建需要root权限。

**Comment by lzjqsdd** [comment]
另外能说下你的系统发行版么？由于目前我使用的还是ubuntu14.04来开发，其他系统测试暂时还不能完全覆盖。
手动在终端执行 pkexec --user root /usr/local/WifiAssist/WifiAssist 帮忙测试下吧。

**Comment by soenter** [comment]
有这个文件/usr/share/polkit-1/actions/com.lzjqsdd.WifiAssist.policy

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
    <action id="org.freedesktop.policykit.pkexec.WifiAssist">
    <description>Run WifiAssist program</description>
    <message>WifiAssist Need Your Authentication~~</message>
    <icon_name>accessories-text-editor</icon_name>
    <defaults>
        <allow_any>auth_admin</allow_any>
        <allow_inactive>auth_admin</allow_inactive>
        <allow_active>auth_admin</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/local/WifiAssist/WifiAssist</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
    </action>
</policyconfig>
```

执行一下命令报：[1]    8302 segmentation fault  sudo WifiAssist

``` bash
sudo rm /usr/local/bin/WifiAssist
sudo ln -s /usr/local/WifiAssist/WifiAssist /usr/local/bin/WifiAssist
```

我用的是v0.6的tag，进入INSTALL目录执行./install.sh安装的

发行版是deepin 15.2

**Comment by soenter** [comment]
手动执行报：[1]    9369 segmentation fault  pkexec --user root /usr/local/WifiAssist/WifiAssist

``` bash
pkexec --user root /usr/local/WifiAssist/WifiAssist 
```

**Comment by lzjqsdd** [comment]
谢谢，如果有迫切需要的话，请先使用create_ap这个项目吧，命令行下操作，WifiAssist主要对其进行封装，我现在在其他机器上测试，排查问题。

**Comment by lzjqsdd** [comment]
请使用master版本 `git clone git@github.com:lzjqsdd/WifiAssist.git`，我在虚拟机及其他物理机测试了，你看下能不能正常运行，可以直接在INSTALL文件夹下 ./WifiAssist执行，如果可以运行再进行安装。

**Comment by soenter** [comment]
还是报错

```
[1]    9018 segmentation fault  ./WifiAssist
```

**Comment by lzjqsdd** [comment]
刚才更新的么？请先删除~/.WifiAssist目录,然后在终端下执行以下命令：

```
ulimit -c unlimited
./WifiAssist
gdb ./WifiAssit core
```

进入gdb后输入where，把结果贴过来我看下问题。

**Comment by soenter** [comment]
界面能启动了，但是点击START后报错，wifi不能用

```
WARN: Your adapter does not fully support AP virtual interface, enabling --no-virt
ERROR: hostapd not found.
Trying to kill wifi.sh instance associated with wlp2s0...
```

**Comment by lzjqsdd** [comment]
hostapd是用来建立热点的工具，需要安装，另外其他几个也需要安装

`sudo apt-get install -y hostapd iproute2 iw iwconfig haveged`
