### ISSUE TITLE
Refusing to render service to dead parents

### ISSUE THREAD

**Issue by SmithTang** [lzjqsdd/WifiAssist#21]
终端运行，点击start过后
![20161001140523](https://cloud.githubusercontent.com/assets/8842710/19012180/6b8b1832-87e0-11e6-8325-1c3bfb125a4d.png)

**Comment by lzjqsdd** [comment]
deepin下会出现这样的问题，主要是由于Polkit引起的，现在还没找到合适的解决方法。（为了不让多次输入密码，使用了gksu,但是出现这个问题了）
