### ISSUE TITLE
启动热点时报错

### ISSUE THREAD

**Issue by ubuntuwbw** [lzjqsdd/WifiAssist#6]
Config dir: /tmp/create_ap.wlan0.conf.Yqyfa4Cb
PID: 5633
Creating a virtual WiFi interface... ap0 created.
Network Manager found, set ap0 as unmanaged device... DONE
RTNETLINK answers: Device or resource busy

ERROR: Maybe your WiFi adapter does not fully support virtual interfaces.
       Try again with --no-virt.

Doing cleanup.. done

**Comment by ubuntuwbw** [comment]
机器是Thinkpad T540P ubuntu14.04 64位

**Comment by lzjqsdd** [comment]
安装以下几个包试试
    sudo apt-get install -y hostapd iproute2 iw iwconfig haveged

**Comment by ubuntuwbw** [comment]
装过了，iwconfig说不存在，其他都装了，还重启了一次

**Comment by ubuntuwbw** [comment]
Config dir: /tmp/create_ap.wlan0.conf.X1mwc5A5
PID: 3528
Creating a virtual WiFi interface... ap0 created.
Network Manager found, set ap0 as unmanaged device... DONE
RTNETLINK answers: Device or resource busy

ERROR: Maybe your WiFi adapter does not fully support virtual interfaces.
       Try again with --no-virt.

Doing cleanup.. done

这是重启后的错误日志

**Comment by lzjqsdd** [comment]
使用--no-virt只能通过一个网卡共享给另一个网卡，无法使用相同的网卡，不过目前考虑大家应该很少使用wlan0接收并创建热点来共享（但不排除），所以这个问题会考虑增加高级设置来处理，近期会提供一个版本测试下。

**Comment by lzjqsdd** [comment]
请尝试最新的测试下吧。
